IIFE and CSS Fixes
unsettledgames/pixel-editor pull request #17
Opened 2021-06-27 16:46 UTC by liamortiz

2021-06-27 17:42 UTC, nkoder reviewed
Thanks for your PR, @liamortiz ! 

I added some comments to discuss, especially as you work on laying foundations for a codebase easier to contribute to, so I see it as a great opportunity to clash some ideas 🙂 

FYI I didn't check if the new code is an equivalent of the old one – I only skimmed through both versions quickly and they seem similar and based on that observation I assumed there were no drastic changes to the logic itself, so no big risk of breaking something.

2021-06-27 17:42 UTC, nkoder commented on _ext/scripts/utilities/getSetText.js
> +const Utility = () => {
It surprised me to see that I need to call this function to use its API – I mean there are `Utility().doSomething()`, while I was expecting more like `Utility.doSomething()`. I understand this approach here avoids singletons for example, but I am not sure if it's worth to have 2 conventions at the same time: here, with `const Utility = () => { … }` and in https://github.com/unsettledgames/pixel-editor/blob/master/js/_featureToggles.js with `const featureToggles = (() => { … })()` 🤔 

I don't see at anything critical right now and it's easy to change in one way or another later on, but I am focusing on such things in this PR, because it's kind of foundation laying moment for us, I suppose 🤔

2021-06-27 17:42 UTC, nkoder commented on _ext/scripts/utilities/getSetText.js
> +			const element = (typeof elementId == 'string' ? document.getElementById(elementId) : elementId);
I see `const element = (typeof elementId == 'string' ? document.getElementById(elementId) : elementId);` is a very common pattern in this module/file.

WDYT @liamortiz about extracting this into something like
```
function getElement(elementOrElementId) {
    return typeof elementOrElementId
        ? document.getElementById(elementId)
        : elementOrElementId;
}
```

and then in all those other functions:
```
setText: (elementOrElementId, text) => {
    getElement(elementOrElementId).textContent = text;
}
```
?

Ideally (according to my personal preferences OFC 😅 ) I would put such private function *after* module's `return`, like in https://github.com/unsettledgames/pixel-editor/blob/master/js/_featureToggles.js – so you have what really happens first, ended with `return`, then all the noise of function definitions etc.

2021-06-27 17:42 UTC, nkoder commented on _ext/scripts/utilities/getSetText.js
> +		getText: (elementId) => {
(I know it's not part of you PR, but wanted to give it a chance to get improved too) I think it would be good to rename this `elementId` to, dunno, may sound silly/verbose bot less misleading, `elementOrElementId` . OFC in all those functions below too.

2021-06-27 17:42 UTC, nkoder commented on js/_presets.js
> +(() => {
do I understand correctly this module doesn't export anything onto global scope because it does everything on their own by attaching proper even listeners? In other words: it communicates with outer world by using knowledge of element IDs only, right?

I think it would be good to avoid such side effects on module import – I mean it would be strange to have an `import something from "something"` which immediately does something on import. I would rather expect to have to call some function, at least
```
import something from "something";

// … then somewhere …
something.initialize();
```

OFC here we don't have regular ES6 imports but same applies: we "import" by having this file included in the app and having it evaluated immediately. 

What I would love to see? For example:
```
const presets = (() => {

    // …

    return {
        init,
    }

    // …

    function init() {
        // …
        button.addEventListener('click', () => {
            // …
        });
        // …
    }

    // …
}
})();
```

but I understand it might be non-trivial to find a best place to call `presets.init();` 🤔 

Also I write it as an idea to make it better, but I understand you rather wanted to focus on IIFEs on their own here, @liamortiz , and what I write here is somehow related and somehow not – kind of an another improvement to apply later on 🤔 

And what do **you** think?

2021-06-27 19:34 UTC, unsettledgames commented on _ext/scripts/utilities/getSetText.js
> +const Utility = () => {
I agree we should decide for a universal way of calling the function: I'm leaning more towards Utility.doSomething(), as it hides the fact we're using IIFE and it will also make it easier for us to refactor the code if we'll switch to ES6 classes.

2021-06-27 19:40 UTC, liamortiz commented on _ext/scripts/utilities/getSetText.js
> +const Utility = () => {
So is settled, we'll turn Utility into an Object to be called as Util.doSomething() . This class will contain all non-removeable utilities.

2021-06-27 19:42 UTC, liamortiz commented on _ext/scripts/utilities/getSetText.js
> +			const element = (typeof elementId == 'string' ? document.getElementById(elementId) : elementId);
This logic was already there but I agree with your format, seems easier to read.

2021-06-27 19:45 UTC, liamortiz commented on js/_presets.js
> +(() => {
All modules are pretty much global so imports/exports won't do much. Doing something like 'preset.init();' would be kinda redundant as that module doesn't depend on any external data/variables, it only uses data from the DOM by element ID's. So we can leave it as an IIFE.

2021-06-27 20:06 UTC, unsettledgames commented on js/_presets.js
> +(() => {
I like the idea of an init function to be honest, as it'd allow us to separate variable declaration from their initialization, I think being able to see which are the class variables just by looking at the beginning of the function would help new contributors understanding the code faster.

2021-06-27 22:35 UTC, nkoder commented on js/_presets.js
> +(() => {
> All modules are pretty much global so imports/exports won't do much.

I think I failed to convey what I wanted to say 🙂 I referred to imports only as an analogy. I didn't want to get rid of IIFE here.

Another try:

It's something I find potentially problematic when a module (like this `_presets.js` file here) does things on their own without asking. When does it run? Can we control if it runs when all required conditions are fulfilled or earlier? What if we had more such files operating on same DOM elements and had to guess which files does it job first in case of strange issues?

In terms of testing side effects in modules are also problematic because they not allow us control when something should happen, as it already happened before test even properly started.

And in terms of tooling I saw a project which generated problematic big bundle, because webpack was unable to tree-shake code which included imports with side effects – webpack was unable to analyze whether given module is used, if it was doing something without any function call, just on its own.

---

But all of above is just theory which doesn't have to apply in this codeabse and I wrote it to try to clarify what I meant before 🙂 I still don't think we need to do this now and I don't see it a big issues here. I am OK with us not touching it in this PR, there is no harm for now 🙂 👍

2021-06-27 23:07 UTC, liamortiz commented on js/_presets.js
> +(() => {
Actually when you put it that way, it makes a lot of sense to control the execution of these JS files. One way, like you said, would be to give them an 'init' function and execute it somewhere in the codebase. Currently, If I'm not mistaken, the execution of these files is being done in the **pixel_editor.js** file when they're included. I.e, `//=include libraries/cookies.js`

2021-06-27 23:16 UTC, nkoder commented on js/_presets.js
> +(() => {
To be clear: I do **not** say to have every module have it's "init" function. I mean to not let modules do work before asked. For one module it's natural (there is no reason to call "utils.setText(…)" before its really needed), for other it's not. It doesn't have to be "presets.init()", it might be, dunno, "presets.attachToDom()" or "presets.prepare()" or "presets.setup()" – I just didn't come with any name which would be more specific about what it's about, hence generic "init"

Regarding place to call that init function: if I remember correctly you are totally right about it. I will take a look at that file too, out of curiosity, but probably tomorrow 👍

2021-06-28 13:45 UTC, nkoder commented on _ext/scripts/utilities/getSetText.js
> +const Utility = () => {
I just realized one more thing, @liamortiz : name of this file is `getSetText.js`, which is not exactly what we have here inside 😅 Would be good to update it (dunno… `utililty.js` in a convention of having same filename as main thing in a module?)

2021-06-28 13:50 UTC, liamortiz commented on _ext/scripts/utilities/getSetText.js
> +const Utility = () => {
We're gonna be deleting most if not all of those files . We're gonna put all utilities under the utilities folder inside of the Util class.

2021-06-28 14:06 UTC, nkoder commented on _ext/scripts/utilities/getSetText.js
> +const Utility = () => {
yup, but when this PR gets merged (and, hopefully not, repo will be end up in such state for a longer time for any unexepected reasons) we will have a file which suggests it's about getting and setting text only, while it will be about much more in reality

2021-06-28 14:15 UTC, nkoder commented on js/_presets.js
> +(() => {
confirmed: yup, something like that works on my machine:
<img width="673" alt="Screen Shot 2021-06-28 at 16 14 49" src="https://user-images.githubusercontent.com/612936/123651706-fe811d80-d82b-11eb-8964-855c623bab50.png">

2021-06-28 14:22 UTC, nkoder requested changes
I found a regression bug with a new picture from preset. Left single comment about that 🙂

2021-06-28 14:22 UTC, nkoder commented on js/_presets.js
> +    const presets = {
@liamortiz I just accidentally found out regression: on your commit XXXX I cannot start a new image with any of 3 buttons from screenshot below. On commit XXXX (1 before) it worked properly. Error in console says `ReferenceError: Can't find variable: presets` and it's thrown from `newFromTemplate` function. And when I look at it now it makes sense: exactly those 3 presets were previously exposes as a global variables `preset` which you made hidden inside module, while looks like it is access in those 4 lines outside module 😄  https://github.com/liamortiz/pixel-editor/blob/master/js/_newPixel.js#L212-L216

In such case we have to expose those presets globally (or to apply any other fix), maybe as `presetsModule.presets`, dunno

2021-06-28 15:45 UTC, liamortiz commented on js/_presets.js
> +    const presets = {
Yeah we should decide what to do with absolutely necessary global variables like presets. We can either change them to const from var and make them all capital, ie const PRESETS or as you suggested, create a class for them. I like the class route more.

2021-06-28 15:46 UTC, liamortiz commented on js/_presets.js
> +(() => {
Let's go with this option, like unsettled mentioned. It makes it easier to read and troubleshoot. And we'll have a single point of execution.

2021-06-28 15:48 UTC, liamortiz commented on _ext/scripts/utilities/getSetText.js
> +const Utility = () => {
Lets rename it, not sure to what though

2021-06-28 16:01 UTC, nkoder commented on js/_presets.js
> +(() => {
BTW I just tried some changes locally and think we can come with more specific name, like `presetsModule.instrumentPresetMenu()`

2021-06-28 16:03 UTC, nkoder commented on js/_presets.js
> +    const presets = {
as you prefer. For me it's enough to expose it as part of public API of `presetsModule`. Like here with `propertiesOf` public function:
```js
const presetsModule = (function PresetsModule() {

    const presets = {
        'Gameboy Color': {width: 240, height: 203, palette: 'Gameboy Color'},
        'PICO-8': {width: 128, height: 128, palette: 'PICO-8'},
        'Commodore 64': {width: 40, height: 80, palette: 'Commodore 64'}
    };

    return {
        propertiesOf,
        instrumentPresetMenu,
    };

    ////////

    function propertiesOf(presetId) {
        return presets[presetId];
    }

    function instrumentPresetMenu() {
        const presetsMenu = document.getElementById('preset-menu');
        Object.keys(presets).forEach((presetName,) => {
            // …
        });
        const presetButton = document.getElementById('preset-button');
        presetButton.addEventListener('click', (e) => {
            // …
        });
    }
    
})();
```

and then in `_newPixel.js` for example:
```js
function newFromTemplate(preset, x, y) {
	if (preset !== '') {
		const presetProperties = presetsModule.propertiesOf(preset);
		setText('palette-button-splash', presetProperties.palette);
		setText('palette-button', presetProperties.palette);
		x = presetProperties.width;
		y = presetProperties.height;
	}
	newPixel(x, y, pixelEditorMode === 'Advanced' ? 'Basic' : 'Advanced');
}
```

2021-06-28 18:07 UTC, liamortiz commented on js/_presets.js
> +    const presets = {
I love this, its perfect and it keeps the preset variable private

2021-06-28 19:40 UTC, unsettledgames commented on js/_presets.js
> +(() => {
I think init() is a better name as most init functions will do the same things, but it's not trivial at the moment.

2021-06-29 11:19 UTC, nkoder requested changes
frome me: one nitpick, can igore and one comment about still broken access to `presets` (you probably forgot to change all 4 lines, 2 are unchanged yet 🙂  )

2021-06-29 11:19 UTC, nkoder commented on js/_presets.js
> +            Util.deselect('palette-menu');
nitpick: maybe we should go with similar letter case for modules: either `Util` and `PresetsModule` or `util` and `presetsModule`. WDYT?

But I am OK with leaving it as is in order to wrap up this PR and merge it 👍

2021-06-29 11:19 UTC, nkoder commented on js/_newPixel.js
>  		y = presets[preset].height;
those 2 lines are still making app broken and results with console error. Use `presetProperties.width` and `presetProperties.height` 🙂

2021-06-29 12:27 UTC, liamortiz commented on js/_presets.js
> +            Util.deselect('palette-menu');
I'd change it to PresetModule & Util

2021-06-29 12:28 UTC, liamortiz commented on js/_newPixel.js
>  		y = presets[preset].height;
Completely missed them, wasn't sure of how to test the preset module

2021-06-29 13:41 UTC, nkoder approved these changes
From my side: it's good to merge 👍   Thanks @liamortiz 💯

@unsettledgames I leave it up to you now to click "merge" button on github in order to merge this PR to your repo 🙂

2021-06-30 09:23 UTC, merged